const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('../.validation/ui/node_modules/jsdom');
const root=path.join(__dirname,'..'),errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));
const dom=new JSDOM(fs.readFileSync(path.join(root,'docs/MiniMax-H3-User-Guide.html'),'utf8'),{url:'https://guide.test/',runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.HTMLElement.prototype.scrollIntoView=()=>{}}});
const w=dom.window,d=w.document,$=id=>d.getElementById(id);
try{
 assert.equal(errors.length,0,errors.map(e=>e.message).join('\n'));
 assert.equal(d.querySelectorAll('.step:not(#help)').length,6);
 assert.equal(d.querySelectorAll('.feature').length,17);
 assert.equal(d.querySelectorAll('#node-list a').length,22);
 assert.equal(d.querySelectorAll('.slide,#next,#previous,.lab').length,0,'No presentation or detached scrolling demo');
 assert.match($('start').textContent,/FL2VA.*REF2VA/s);
 assert.match($('start').textContent,/56 frames/);
 d.querySelector('[data-flow="save"]').click();assert.match($('flow-caption').textContent,/writes/);
 assert(d.querySelector('[data-stage="save"]').classList.contains('active'));
 d.querySelector('[data-mode="reference"]').click();assert.match($('mode-model').textContent,/REF2VA/);
 assert.match($('mode-prompt').textContent,/<Picture 1>/,'Reference tokens remain literal text');
 d.querySelector('[data-mode="opening"]').click();assert.match($('mode-input').textContent,/opening frame/);
 d.querySelector('[data-join="chained"]').click();assert.match($('join-caption').textContent,/trim the prefix/);
 d.querySelector('[data-preview="full"]').click();assert.equal($('preview-demo').querySelectorAll('.dim').length,0);
 d.querySelector('[data-preview="latest"]').click();assert.equal($('preview-demo').querySelectorAll('.dim').length,2);
 assert.match($('preview-caption').textContent,/not transferred/);
 $('search').value='LoRA';$('search').dispatchEvent(new w.Event('input'));assert.equal($('feature-first-video').hidden,false);
 $('search').value='zzzznotfound';$('search').dispatchEvent(new w.Event('input'));assert.equal($('empty').hidden,false);
 d.querySelector('[data-feature="face"]').click();assert.equal($('feature-face').open,true);assert.equal($('feature-face').hidden,false);assert.equal($('search').value,'');
 $('motion').click();assert(d.body.classList.contains('motion-paused'));
 const workflow=JSON.parse($('workflow-data').textContent);assert.deepEqual(workflow,JSON.parse(fs.readFileSync(path.join(root,'workflows/MiniMax H3 Start Here.json'),'utf8')));
 let downloaded=false;w.URL.createObjectURL=()=>{downloaded=true;return 'blob:test'};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};
 d.querySelector('[data-action="download-workflow"]').click();assert(downloaded);
 $('feature-refine').hidden=true;w.dispatchEvent(new w.Event('beforeprint'));assert([...d.querySelectorAll('details')].every(e=>e.open&&!e.hidden));w.dispatchEvent(new w.Event('afterprint'));assert.equal($('feature-refine').hidden,true);
 assert.equal(d.querySelectorAll('script[src],link[rel=stylesheet]').length,0);
 assert.equal(d.querySelectorAll('img').length,1);assert(d.querySelector('img').src.startsWith('data:image/png;base64,'),'Editor screenshot is embedded for offline use');
 assert.equal(errors.length,0,errors.map(e=>e.message).join('\n'));
 console.log('Practical guide passed: connected recipe, model families, joins, latest/full transfer, all 22 tools, search, workflow download and print.');
}catch(e){console.error(e);process.exitCode=1}finally{dom.window.close()}
