// Run: node validation/test_editor.cjs (jsdom@26 in .validation/ui).
const {JSDOM} = require('../.validation/ui/node_modules/jsdom');
const fs = require('fs');
const assert = require('assert');
const dom = new JSDOM('<!doctype html><body></body>', {url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});
const w = dom.window;
const problems = [];
w.alert = message => problems.push(message);
w.HTMLCanvasElement.prototype.getContext = () => new Proxy({}, {get: (_,key) => key === 'measureText' ? text => ({width:text.length*7}) : () => {}});
w.app = {registerExtension: extension => {w.extension=extension;},graph:{links:{},getNodeById:()=>null,setDirtyCanvas:()=>{}},canvas:{setDirty:()=>{}}};
const listeners = new Map();
let submittedDraft;
w.api = {apiURL: url=>url,addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:(name)=>listeners.delete(name),fetchApi:async (url,options={}) => {
  let result = [];
  if (url.includes('waveform')) result={duration:5,peaks:[0,.5,1,.5]};
  if (url.includes('media/upload')) result={name:'tail.mp4',subfolder:'minimax_assets',media_type:'video'};
  if (url.includes('source/info')) result={duration:60,width:960,height:544};
  if (url.includes('forge/draft')) result={context_key:'context',count:1,shots:[{prompt:'Drafted action',type:'T2VA',duration:5}]};
  if (url.includes('forge/apply')) { const body=JSON.parse(options.body); submittedDraft=body.draft; result={timeline:{...body.timeline,clips:[{id:'clip_1',...body.draft.shots[0]}]}}; }
  return {ok:true,json:async()=>result};
}};
w.eval(fs.readFileSync('web/js/minimax_locale.js','utf8').replace('export function','function'));
w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.load=()=>{};
w.eval(fs.readFileSync('web/js/minimax_preview.js','utf8').replace('export function','function'));
w.eval(fs.readFileSync('web/js/minimax_timeline.js','utf8').replace('export function','function'));
w.eval(fs.readFileSync('web/js/minimax_director.js','utf8').replace(/^import .*;\r?\n/gm,''));
const refPool={id:20,type:'MiniMaxH3RefPack',inputs:[{name:'image_1',link:11},{name:'image_2',link:null},{name:'video_1',link:null}],widgets:[{name:'image_1_name',value:'Alice'},{name:'refmod_1',value:'None'},{name:'refmod_2',value:'None'}]};
const imageLoader={id:21,type:'LoadImage',widgets:[{name:'image',value:'alice.png'}]};
w.app.graph.links={10:{origin_id:20},11:{origin_id:21}};
w.app.graph.getNodeById=id=>id===20?refPool:id===21?imageLoader:null;
const initial = {version:2,project_id:'editor',clips:[{id:'clip_1',type:'I2VA',prompt:'Original user text',duration:5,seed:'18446744073709551615',ref_ids:['image_1']}],references:[{id:'uploaded',type:'image',filename:'example.png',name:'Subject'}]};
const timeline = {name:'timeline_data',value:JSON.stringify(initial)};
const node = {id:7,type:'MiniMaxH3MasterDirector',comfyClass:'MiniMaxH3MasterDirector',widgets:[timeline,{name:'builder_state',value:'{}'}],inputs:[{name:'ref_pack',link:10}],outputs:[],size:[1200,800],setSize(value){this.size=value;},setDirtyCanvas(){},addDOMWidget(name,type,element){w.document.body.appendChild(element); const widget={name,type,element};this.widgets.push(widget); return widget;}};
(async()=>{
  const legacy = {nodes:[{type:'MiniMaxH3MasterDirector'}]};
  w.extension.beforeConfigureGraph(legacy); assert.strictEqual(legacy.nodes[0].type,'MiniMaxH3MasterNode');
  const settingsValues=[1344,768,24,25,1,'euler','simple',12,3,0,'All-in-One Generation','simple','full_batch','Motion Context (Chained)','22','full'];
  const oldExporter=[24,'H.264','mp4','8-bit',21,'Standard',false,true,'video/test',true,false,false,'Auto','192k',false,false];
  const oldGraph={nodes:[{type:'MiniMaxH3DirectorSettings',widgets_values:[...settingsValues]},{type:'MiniMaxH3VideoCombine',widgets_values:[...oldExporter]}]};
  w.extension.beforeConfigureGraph(oldGraph);
  assert.strictEqual(oldGraph.nodes[0].widgets_values[10],'fixed');
  assert.strictEqual(oldGraph.nodes[0].widgets_values_named.generation_mode,'All shots');
  assert.strictEqual(oldGraph.nodes[1].widgets_values[3],'ffmpeg');
  assert.strictEqual(oldGraph.nodes[1].widgets_values[4],'8-bit');
  w.extension.beforeConfigureGraph(oldGraph);assert.strictEqual(oldGraph.nodes[0].widgets_values.length,11);
  const namedLegacy={nodes:[{type:'MiniMaxH3DirectorSettings',widgets_values:[...settingsValues],widgets_values_named:{run_mode:'clip_by_clip',execution_mode:'Conditioning Guide Output',seed:'18446744073709551615'}}]};
  w.extension.beforeConfigureGraph(namedLegacy);
  assert.equal(namedLegacy.nodes[0].widgets_values_named.generation_mode,'Conditioning only','Named legacy controls migrate without shifting prompt mode into generation mode');
  assert.equal(namedLegacy.nodes[0].widgets_values_named.seed,'18446744073709551615');
  const noSeedControl={nodes:[{type:'MiniMaxH3DirectorSettings',widgets_values:[1344,768,24,25,1,'euler','simple',12,3,0,'All shots','Independent (No Continuity)','22']}]};
  w.extension.beforeConfigureGraph(noSeedControl);
  assert.equal(noSeedControl.nodes[0].widgets_values_named.generation_mode,'All shots');
  const migratedMaster={id:5,type:'MiniMaxH3MasterNode',inputs:[{name:'config',link:12}],widgets_values:[JSON.stringify({clips:[{id:'m',continuity:true}]}),'{}']};
  const migratedSettings={id:4,...namedLegacy.nodes[0]};
  const migrationGraph={nodes:[migratedSettings,migratedMaster],links:[[12,4,0,5,4,'MMX_DIRECTOR_CONFIG']]};
  w.extension.beforeConfigureGraph(migrationGraph);
  const migratedState=JSON.parse(migratedMaster.widgets_values[0]);
  assert.equal(migratedState.generation_mode,'Conditioning only');
  assert.equal(migratedState.clips[0].continuity_mode,'Motion Context (Chained)');
  assert.equal(migratedState.clips[0].context_length,22);
  function Exporter(){this.widgets=[{name:'quality',value:21},{name:'bit_depth',value:'10-bit'},{name:'encoder_backend',value:'pyav'},{name:'save_output',value:false},{name:'control_after_generate',value:'fixed',options:{serialize:false}},{name:'preview',value:'not_saved',serialize:false}];}
  Exporter.prototype.onSerialize=function(data){data.other_extension='preserved';};
  Exporter.prototype.onConfigure=function(){this.widgets[0].value='wrong positional value';};
  await w.extension.beforeRegisterNodeDef(Exporter,{name:'MiniMaxH3VideoCombine'});
  const exporter=new Exporter(),serialized={};exporter.onSerialize(serialized);
  assert.strictEqual(serialized.other_extension,'preserved');
  assert.strictEqual(serialized.widgets_values_named.save_output,false);
  assert.strictEqual(serialized.widgets_values_named.control_after_generate,'fixed');
  assert.strictEqual(serialized.widgets_values_named.preview,undefined);
  exporter.widgets.reverse();exporter.onConfigure(serialized);
  assert.strictEqual(exporter.widgets.find(widget=>widget.name==='quality').value,21);
  assert.strictEqual(exporter.widgets.find(widget=>widget.name==='bit_depth').value,'10-bit');
  w.extension.nodeCreated(node);
  await new Promise(resolve=>setTimeout(resolve,40));
  assert(w.document.querySelector('.mmx-director-root'),'Editor mounts');
  const writingPanel=w.document.querySelector('.mmx-edit-main');
  assert(writingPanel.querySelector('.mmx-prompt-inspector'),'Prompt belongs to the primary writing area');
  assert(writingPanel.querySelector('.mmx-inspector-cards-grid'),'Duration and seed stay beside the prompt');
  assert(!writingPanel.querySelector('.mmx-section'),'Advanced sections cannot push the prompt down');
  const chooseTool=label=>w.document.querySelector(`[role=tab][data-tool="${label}"]`);
  chooseTool('Look').click();
  assert.strictEqual(w.document.querySelector('.mmx-edit-main'),writingPanel,'Switching tools preserves the actual writing DOM and caret');
  assert.equal(chooseTool('Look').getAttribute('aria-selected'),'true');
  assert.equal(w.document.querySelectorAll('.mmx-tool-content > details:not([hidden])').length,1);
  assert(w.document.querySelector('.mmx-edit-main .mmx-textarea'),'Prompt remains mounted when tools change');
  chooseTool('Look').onkeydown({key:'ArrowRight',preventDefault(){}});
  assert.equal(chooseTool('LoRAs').getAttribute('aria-selected'),'true','Keyboard moves between tool tabs');
  chooseTool('Project').click();
  assert.equal(w.document.querySelectorAll('.mmx-section').length,5,'Project configuration has one surface');
  assert(w.document.querySelector('[role=tabpanel][aria-labelledby$="project-panel-tab"] > .mmx-section-body'));
  const help=w.document.querySelector('.mmx-tools-heading button');help.click();
  assert(w.document.querySelector('.mmx-edit-tools').classList.contains('mmx-show-help'));
  help.click();assert.equal(help.getAttribute('aria-pressed'),'false');
  const writer=w.document.querySelector('.mmx-edit-main .mmx-textarea');writer.setSelectionRange(2,8);
  chooseTool('Continuity').click();
  assert.equal(writer.selectionStart,2);assert.equal(writer.selectionEnd,8,'Tab navigation preserves the prompt selection');
  assert(!w.document.body.textContent.includes('Canvas source'),'Canvas has one owner in Settings');
  assert(!w.document.body.textContent.includes('Choose saved take for continuation'));
  assert(!w.document.body.textContent.includes('Create project exporter'));
  assert([...w.document.querySelectorAll('summary')].some(el=>el.textContent==='Files & recovery'));
  const continuationFile=w.document.querySelector('.mmx-continue-video').closest('.mmx-section-body').querySelector('input[type="file"]');
  Object.defineProperty(continuationFile,'files',{value:[new w.File(['video'],'ending.mp4',{type:'video/mp4'})]});
  await continuationFile.onchange();
  assert.equal(JSON.parse(timeline.value).clips[0].continuation_source.filename,'minimax_assets/tail.mp4');
  assert.equal(JSON.parse(timeline.value).clips[0].continuity_mode,'Motion Context (Chained)');
  [...w.document.querySelectorAll('button')].find(el=>el.textContent==='Use previous timeline clip').click();
  assert(!JSON.parse(timeline.value).clips[0].continuation_source);
  const freshMethod=w.document.querySelector('.mmx-shot-continuity-mode');freshMethod.value='Independent (No Continuity)';freshMethod.onchange();
  const videoImport=w.document.querySelector('.mmx-toolbar input[type="file"]');
  Object.defineProperty(videoImport,'files',{value:[new w.File(['video'],'existing.mp4',{type:'video/mp4'})]});
  await videoImport.onchange();
  const imported=JSON.parse(timeline.value).clips[1];assert(imported.locked && imported.type==='V2V');
  assert.equal(imported.source.filename,'minimax_assets/tail.mp4');
  assert.equal(imported.duration,60);
  timeline.value=JSON.stringify(initial);node.__mmxDirectorRefresh();
  const initialTags=[...w.document.querySelectorAll('.mmx-quick-tag-btn')].map(el=>el.textContent);
  assert(initialTags.some(text=>text.includes('Alice') && text.includes('<Picture 1>')));
  assert(!initialTags.some(text=>text.includes('<Video') || text.includes('<Audio') || text.includes('<Picture 2>')));
  const editorRoot=w.document.querySelector('.mmx-director-root');
  assert.equal(editorRoot.querySelector('.mmx-language-select').parentElement.className,'mmx-toolbar-right');
  const editorWidget=node.widgets.find(widget=>widget.name==='master_director_ui');
  editorWidget.draw(null,{inputs:Array(18).fill({}),outputs:[]},1200,0,600);
  assert.equal(editorWidget.last_y,370,'Editor starts below all socket rows');
  assert.equal(editorRoot.style.height,editorRoot.style.maxHeight,'Editor stays inside its allocated node area');
  assert(editorRoot.querySelector('.mmx-time-tick.major span'), 'Ruler labels use browser text');
  assert(!editorRoot.querySelector('.mmx-ruler-canvas'), 'No stretched bitmap ruler');
  const rulerLane=editorRoot.querySelector('.mmx-ruler-lane');
  const timelineZoom=editorRoot.querySelector('.mmx-zoom-slider');
  assert.equal(timelineZoom.value,'3.0','Short clips start at a readable timeline scale');
  assert(editorRoot.querySelector('.mmx-shot-cover'),'Assigned pool image appears in the shot card');
  timelineZoom.value='1.0'; timelineZoom.oninput();
  const timelinePanel=editorRoot.querySelector('.mmx-multitrack-panel');
  Object.defineProperty(timelinePanel,'clientWidth',{value:918,configurable:true});
  const ruler=editorRoot.querySelector('.mmx-time-ruler');
  ruler.getBoundingClientRect=()=>({left:100,width:parseFloat(ruler.style.width)*1.55});
  timelineZoom.oninput();
  const endpoint=ruler.querySelector('.endpoint');
  assert.equal(endpoint.textContent,'13s','Labels extend beyond the five-second shot to the visible interval end');
  assert.equal(parseFloat(endpoint.style.left),parseFloat(ruler.style.width),'Right edge ends on a labeled interval');
  const pixelsPerSecond=parseFloat(ruler.style.width)/13;
  rulerLane.dispatchEvent(new w.MouseEvent('mousedown',{clientX:100+2.5*pixelsPerSecond*1.55,bubbles:true}));
  assert.equal(editorRoot.querySelector('.mmx-timecode-display').textContent,'00:00:02:12','Scrubbing accounts for 155% graph zoom');
  w.dispatchEvent(new w.MouseEvent('mousemove',{clientX:50}));
  assert.equal(editorRoot.querySelector('.mmx-timecode-display').textContent,'00:00:00:00');
  assert.equal(editorRoot.querySelector('.mmx-playhead-needle').style.left,'130px','Playhead includes the actual header width and new timeline padding');
  w.dispatchEvent(new w.MouseEvent('mousemove',{clientX:100+parseFloat(ruler.style.width)*1.55}));
  assert.equal(editorRoot.querySelector('.mmx-timecode-display').textContent,'00:00:13:00','Empty visible ruler space remains scrubbable');
  w.dispatchEvent(new w.MouseEvent('mouseup'));
  assert.strictEqual(JSON.parse(timeline.value).clips[0].seed,'18446744073709551615');
  assert.deepStrictEqual(JSON.parse(timeline.value).clips[0].ref_ids,['image_1']);
  const language=w.document.querySelector('select[title="UI language"]');
  language.value='ar'; language.onchange();
  assert(w.document.body.textContent.includes('أدوات المشروع'));
  assert(w.document.body.textContent.includes('Original user text'));
  language.value='en';language.onchange();
  w.confirm=()=>true;
  const inspectorDelete=()=>[...editorRoot.querySelectorAll('button')].find(el=>el.textContent==='Delete Clip');
  assert(inspectorDelete(), 'The last shot has a visible Delete Clip action');
  [...editorRoot.querySelectorAll('button')].find(el=>el.textContent.includes('Duplicate Clip')).click();
  [...editorRoot.querySelectorAll('button')].find(el=>el.textContent.includes('Duplicate Clip')).click();
  const generationControl=editorRoot.querySelector('.mmx-generation-mode');
  assert(generationControl,'Generation mode is prominently mounted in the Master');
  generationControl.value='All shots';generationControl.onchange();
  assert.equal(JSON.parse(timeline.value).generation_mode,'All shots');
  generationControl.value='Next shot';generationControl.onchange();
  const continuityControl=editorRoot.querySelector('.mmx-shot-continuity-mode');
  continuityControl.value='Motion Context (Chained)';continuityControl.onchange();
  const videoContext=editorRoot.querySelector('.mmx-shot-context_length');videoContext.value='39';videoContext.onchange();
  const audioContext=editorRoot.querySelector('.mmx-shot-audio_context_length');audioContext.value='5';audioContext.onchange();
  assert.equal(editorRoot.querySelector('.mmx-continuity-overlay.video').dataset.frames,'39');
  assert.equal(editorRoot.querySelector('.mmx-continuity-overlay.audio').dataset.frames,'5');
  assert([...editorRoot.querySelectorAll('details.mmx-section > summary')].some(s=>s.textContent.includes('Continuity')));
  const off=editorRoot.querySelector('.mmx-shot-continuity-mode');off.value='Independent (No Continuity)';off.onchange();
  assert.equal(editorRoot.querySelectorAll('.mmx-continuity-overlay').length,0);
  const beforeDrag=JSON.parse(timeline.value).clips;
  const blocks=[...editorRoot.querySelectorAll('.mmx-shot-block')];
  blocks.forEach((el,index)=>{Object.defineProperty(el,'offsetWidth',{value:160}); el.getBoundingClientRect=()=>({left:100+index*254,width:248,right:348+index*254});});
  const dragBlock=blocks[0];
  dragBlock.dispatchEvent(new w.MouseEvent('pointerdown',{clientX:140,button:0,bubbles:true}));
  w.dispatchEvent(new w.MouseEvent('pointermove',{clientX:890}));
  assert(editorRoot.querySelectorAll('.mmx-dragging').length===4,'All reference lanes move with the shot');
  w.dispatchEvent(new w.MouseEvent('pointerup',{clientX:890}));
  const afterDrag=JSON.parse(timeline.value).clips;
  assert.deepStrictEqual(afterDrag.map(c=>c.id),[beforeDrag[1].id,beforeDrag[2].id,beforeDrag[0].id]);
  assert.deepStrictEqual(afterDrag[2].ref_ids,['image_1']);
  assert.equal(afterDrag[2].seed,beforeDrag[0].seed); assert.equal(afterDrag[2].duration,5,'Dragging does not resize');
  const area=editorRoot.querySelector('.mmx-multitrack-panel');
  assert(area);
  area.getBoundingClientRect=()=>({left:0,right:1000,top:0,bottom:400,width:1000});
  const cancelled=editorRoot.querySelector('.mmx-shot-block');
  const orderBeforeCancel=JSON.parse(timeline.value).clips.map(c=>c.id);
  cancelled.dispatchEvent(new w.MouseEvent('pointerdown',{clientX:150,clientY:100,button:0,bubbles:true}));
  w.dispatchEvent(new w.MouseEvent('pointermove',{clientX:400,clientY:100}));
  assert.equal(editorRoot.querySelectorAll('.mmx-dragging').length,4);
  w.dispatchEvent(new w.MouseEvent('pointermove',{clientX:1200,clientY:100}));
  assert.equal(editorRoot.querySelectorAll('.mmx-dragging').length,0,'Leaving the editor restores all four clip lanes');
  assert([...editorRoot.querySelectorAll('.mmx-subtrack-block')].every(el=>!el.style.transform));
  assert.deepStrictEqual(JSON.parse(timeline.value).clips.map(c=>c.id),orderBeforeCancel,'An outside drop leaves shot order intact');
  cancelled.dispatchEvent(new w.MouseEvent('pointerdown',{clientX:150,clientY:100,button:0,bubbles:true}));
  w.dispatchEvent(new w.MouseEvent('pointermove',{clientX:400,clientY:100}));
  w.dispatchEvent(new w.Event('blur'));
  assert.equal(editorRoot.querySelectorAll('.mmx-dragging').length,0,'Losing window focus restores clips');
  const resized=[...editorRoot.querySelectorAll('.mmx-shot-block')][2];
  Object.defineProperty(resized,'offsetWidth',{value:160});resized.getBoundingClientRect=()=>({width:248});
  resized.querySelector('.mmx-clip-handle-right').dispatchEvent(new w.MouseEvent('mousedown',{clientX:500,bubbles:true}));
  w.dispatchEvent(new w.MouseEvent('mousemove',{clientX:549.6}));w.dispatchEvent(new w.MouseEvent('mouseup'));
  assert.equal(JSON.parse(timeline.value).clips[2].duration,5.5,'Resize accounts for 155% graph zoom');
  inspectorDelete().click(); inspectorDelete().click(); inspectorDelete().click();
  assert.equal(JSON.parse(timeline.value).clips.length,0,'The final shot can be deleted');
  node.__mmxDirectorRefresh();
  assert.equal(JSON.parse(timeline.value).clips.length,0,'Reload keeps an intentionally empty timeline');
  assert(editorRoot.textContent.includes('No clips.'));
  timeline.value=JSON.stringify(initial); node.__mmxDirectorRefresh();
  const button=text=>[...w.document.querySelectorAll('button')].find(element=>element.textContent===text);
  assert(!editorRoot.textContent.includes('Prompt Forge'));
  assert(!editorRoot.textContent.includes('RefMod library'));
  const clipMode=editorRoot.querySelector('.mmx-inspector-header select');clipMode.value='T2V';clipMode.onchange();
  assert(editorRoot.querySelector('.mmx-local-refs-pool').hidden,'Text-only clips do not offer references');
  assert.strictEqual(problems.length,0,problems.join('\n'));
  assert.equal(editorRoot.querySelector('.mmx-smart-preview'),null,'Preview is a separate node');
  assert(!editorRoot.textContent.includes('Upload reference'));
  assert(!editorRoot.textContent.includes('Upload and edit references'));
  const nav=editorRoot.querySelector('.mmx-toolbar');
  assert.deepStrictEqual([...nav.querySelectorAll('button')].map(el=>el.textContent),['Add video clip'],'Navigation has no duplicated project or reference actions');
  let graphWheel=0;const wheelListener=()=>graphWheel++;w.document.body.addEventListener('wheel',wheelListener);
  const scrollWheel=new w.WheelEvent('wheel',{bubbles:true,cancelable:true,deltaY:80});
  editorRoot.querySelector('.mmx-tool-content').dispatchEvent(scrollWheel);
  assert.equal(graphWheel,0,'Panel scrolling cannot zoom the graph');
  assert(!scrollWheel.defaultPrevented,'Native panel scrolling remains enabled');w.document.body.removeEventListener('wheel',wheelListener);
  assert(editorRoot.querySelector('.mmx-generation-bar').textContent.includes('Selected clips only'),'Eligibility is beside generation scheduling');
  const filesPanel=[...editorRoot.querySelectorAll('details')].find(el=>el.querySelector(':scope > summary')?.textContent==='Files & recovery');
  assert.equal([...filesPanel.querySelectorAll('button')].filter(el=>el.textContent==='Export project').length,1);
  assert.equal([...filesPanel.querySelectorAll('button')].filter(el=>el.textContent==='Import project').length,1);
  assert(filesPanel.querySelector('.mmx-export-media'),'Export format is configured at its sole action');
  assert(!editorRoot.textContent.includes('Export with media') && !editorRoot.textContent.includes('Import media pack'));
  const previousFetch=w.api.fetchApi, calls=[];
  w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};
  w.HTMLAnchorElement.prototype.click=()=>{};
  w.api.fetchApi=async(url)=>{calls.push(url);return {ok:true,json:async()=>({ok:true,project:{}}),blob:async()=>new w.Blob(['archive'])};};
  const exportProject=button('Export project'),mediaChoice=filesPanel.querySelector('.mmx-export-media');
  await exportProject.onclick();
  assert.equal(calls.pop(),'/minimax_director/project/portable/export');
  mediaChoice.checked=false;await exportProject.onclick();
  assert.equal(calls.pop(),'/minimax_director/project/export');
  assert(!exportProject.disabled);w.api.fetchApi=previousFetch;
  assert.equal(editorRoot.querySelectorAll('input[type="file"]').length,2,'Only video import and continuation use local file pickers');
  const quick=[...editorRoot.querySelectorAll('.mmx-quick-tag-btn')].map(el=>el.textContent);
  assert.equal(quick.length,0,'No reference tokens are offered for an unassigned draft shot');
  assert(!quick.some(text=>text.includes('<Video') || text.includes('<Audio') || text.includes('<Picture 2>')));
  node.onRemoved();assert.strictEqual(listeners.size,0);
  w.prompt=()=> '2';
  const sourceState={...initial,clips:[{id:'clip_1',name:'Source',type:'V2V',source:{filename:'source.mp4'},source_start:3,source_end:9,duration:6,prompt:'Keep this action',ref_ids:['image_1'],validated:true}]};
  const sourceTimeline={name:'timeline_data',value:JSON.stringify(sourceState)};
  const sourceNode={...node,id:8,widgets:[sourceTimeline,{name:'builder_state',value:'{}'}],__mmxDirectorMounted:false,__mmxShotListener:null,__mmxLocaleCleanup:null,onRemoved:undefined};
  w.extension.nodeCreated(sourceNode);
  await new Promise(resolve=>setTimeout(resolve,20));
  button('Split into equal ranges').onclick();
  const split=JSON.parse(sourceTimeline.value).clips;
  assert.deepStrictEqual(split.map(shot=>[shot.source_start,shot.source_end]),[[3,6],[6,9]]);
  assert(split.every(shot=>shot.prompt==='Keep this action' && !shot.validated));
  assert(split.every(shot=>shot.ref_ids[0]==='image_1'));
  sourceTimeline.value=JSON.stringify({...sourceState,clips:[{...sourceState.clips[0],locked:true}]});
  sourceNode.__mmxDirectorRefresh();
  const lockedRange=[...w.document.querySelectorAll('fieldset')].find(el=>el.querySelector('legend')?.textContent==='Source video range');
  assert(lockedRange,'Locked source inspector renders without referencing a removed upload control');
  assert([...lockedRange.querySelectorAll('input,button,select')].every(el=>el.disabled));
  sourceNode.onRemoved();assert.strictEqual(listeners.size,0);
  dom.window.close();console.log('Editor mount, migration, uint64 persistence, language, file continuation, actual source splitting, and cleanup passed');
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
