// Run: node validation/test_editor.cjs (jsdom@26 in .validation/ui).
const {JSDOM} = require('../.validation/ui/node_modules/jsdom');
const fs = require('fs');
const assert = require('assert');
const dom = new JSDOM('<!doctype html><body></body>', {url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});
const w = dom.window;
const problems = [];
w.alert = message => problems.push(message);
w.HTMLCanvasElement.prototype.getContext = () => new Proxy({}, {get: (_,key) => key === 'measureText' ? text => ({width:text.length*7}) : () => {}});
w.app = {registerExtension: extension => {w.extension=extension;},graph:{links:{},getNodeById:()=>null,setDirtyCanvas:()=>{}},canvas:{setDirty:()=>{}}};
const listeners = new Map();
let submittedDraft;
w.api = {apiURL: url=>url,addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:(name)=>listeners.delete(name),fetchApi:async (url,options={}) => {
  let result = [];
  if (url.includes('waveform')) result={duration:5,peaks:[0,.5,1,.5]};
  if (url.includes('forge/draft')) result={context_key:'context',count:1,shots:[{prompt:'Drafted action',type:'T2VA',duration:5}]};
  if (url.includes('forge/apply')) { const body=JSON.parse(options.body); submittedDraft=body.draft; result={timeline:{...body.timeline,clips:[{id:'clip_1',...body.draft.shots[0]}]}}; }
  return {ok:true,json:async()=>result};
}};
w.eval(fs.readFileSync('web/js/minimax_locale.js','utf8').replace('export function','function'));
w.eval(fs.readFileSync('web/js/minimax_director.js','utf8').replace(/^import .*;\r?\n/gm,''));
const initial = {version:2,project_id:'editor',clips:[{id:'clip_1',type:'T2VA',prompt:'Original user text',duration:5,seed:'18446744073709551615',ref_ids:['uploaded']}],references:[{id:'uploaded',type:'image',filename:'example.png',name:'Subject'}]};
const timeline = {name:'timeline_data',value:JSON.stringify(initial)};
const node = {id:7,type:'MiniMaxH3MasterDirector',comfyClass:'MiniMaxH3MasterDirector',widgets:[timeline,{name:'builder_state',value:'{}'}],inputs:[],outputs:[],size:[1200,800],setSize(value){this.size=value;},setDirtyCanvas(){},addDOMWidget(name,type,element){w.document.body.appendChild(element); const widget={name,type,element};this.widgets.push(widget); return widget;}};
(async()=>{
  const legacy = {nodes:[{type:'MiniMaxH3MasterDirector'}]};
  w.extension.beforeConfigureGraph(legacy); assert.strictEqual(legacy.nodes[0].type,'MiniMaxH3MasterNode');
  const settingsValues=[1344,768,24,25,1,'euler','simple',12,3,0,'All-in-One Generation','simple','full_batch','Motion Context (Chained)','22','full'];
  const oldExporter=[24,'H.264','mp4','8-bit',21,'Standard',false,true,'video/test',true,false,false,'Auto','192k',false,false];
  const oldGraph={nodes:[{type:'MiniMaxH3DirectorSettings',widgets_values:[...settingsValues]},{type:'MiniMaxH3VideoCombine',widgets_values:[...oldExporter]}]};
  w.extension.beforeConfigureGraph(oldGraph);
  assert.strictEqual(oldGraph.nodes[0].widgets_values[10],'fixed');
  assert.strictEqual(oldGraph.nodes[0].widgets_values[11],'All-in-One Generation');
  assert.strictEqual(oldGraph.nodes[1].widgets_values[3],'ffmpeg');
  assert.strictEqual(oldGraph.nodes[1].widgets_values[4],'8-bit');
  w.extension.beforeConfigureGraph(oldGraph);assert.strictEqual(oldGraph.nodes[0].widgets_values.length,17);
  function Exporter(){this.widgets=[{name:'quality',value:21},{name:'bit_depth',value:'10-bit'},{name:'encoder_backend',value:'pyav'},{name:'save_output',value:false},{name:'control_after_generate',value:'fixed',options:{serialize:false}},{name:'preview',value:'not_saved',serialize:false}];}
  Exporter.prototype.onSerialize=function(data){data.other_extension='preserved';};
  Exporter.prototype.onConfigure=function(){this.widgets[0].value='wrong positional value';};
  await w.extension.beforeRegisterNodeDef(Exporter,{name:'MiniMaxH3VideoCombine'});
  const exporter=new Exporter(),serialized={};exporter.onSerialize(serialized);
  assert.strictEqual(serialized.other_extension,'preserved');
  assert.strictEqual(serialized.widgets_values_named.save_output,false);
  assert.strictEqual(serialized.widgets_values_named.control_after_generate,'fixed');
  assert.strictEqual(serialized.widgets_values_named.preview,undefined);
  exporter.widgets.reverse();exporter.onConfigure(serialized);
  assert.strictEqual(exporter.widgets.find(widget=>widget.name==='quality').value,21);
  assert.strictEqual(exporter.widgets.find(widget=>widget.name==='bit_depth').value,'10-bit');
  w.extension.nodeCreated(node);
  await new Promise(resolve=>setTimeout(resolve,40));
  assert(w.document.querySelector('.mmx-director-root'),'Editor mounts');
  assert.strictEqual(JSON.parse(timeline.value).clips[0].seed,'18446744073709551615');
  assert.deepStrictEqual(JSON.parse(timeline.value).clips[0].ref_ids,['uploaded']);
  const language=w.document.querySelector('select[title="UI language"]');
  language.value='ar'; language.onchange();
  assert(w.document.body.textContent.includes('أدوات المشروع'));
  assert(w.document.body.textContent.includes('Original user text'));
  language.value='en';language.onchange();
  const button=text=>[...w.document.querySelectorAll('button')].find(element=>element.textContent===text);
  await button('Create draft').onclick();
  const review=[...w.document.querySelectorAll('fieldset')].find(element=>element.textContent.includes('Shot 1'));
  assert(review,'Draft has editable shot controls');
  const prompt=review.querySelector('textarea');prompt.value='Reviewed action';prompt.oninput();
  await button('Apply reviewed draft').onclick();
  assert.strictEqual(submittedDraft.shots[0].prompt,'Reviewed action');
  assert.strictEqual(JSON.parse(timeline.value).clips[0].prompt,'Reviewed action');
  assert.strictEqual(problems.length,0,problems.join('\n'));
  node.onRemoved();assert.strictEqual(listeners.size,0);
  w.prompt=()=> '2';
  const sourceState={...initial,clips:[{id:'clip_1',name:'Source',type:'V2V',source:{filename:'source.mp4'},source_start:3,source_end:9,duration:6,prompt:'Keep this action',ref_ids:['uploaded'],validated:true}]};
  const sourceTimeline={name:'timeline_data',value:JSON.stringify(sourceState)};
  const sourceNode={...node,id:8,widgets:[sourceTimeline,{name:'builder_state',value:'{}'}],__mmxDirectorMounted:false,__mmxShotListener:null,__mmxLocaleCleanup:null,onRemoved:undefined};
  w.extension.nodeCreated(sourceNode);
  await new Promise(resolve=>setTimeout(resolve,20));
  button('Split into equal ranges').onclick();
  const split=JSON.parse(sourceTimeline.value).clips;
  assert.deepStrictEqual(split.map(shot=>[shot.source_start,shot.source_end]),[[3,6],[6,9]]);
  assert(split.every(shot=>shot.prompt==='Keep this action' && !shot.validated));
  assert(split.every(shot=>shot.ref_ids[0]==='uploaded'));
  sourceNode.onRemoved();assert.strictEqual(listeners.size,0);
  dom.window.close();console.log('Editor mount, migration, uint64 persistence, language, draft review, actual source splitting, and cleanup passed');
})().catch(error=>{console.error(error);dom.window.close();process.exitCode=1;});
